# Generated by Django 4.0.2 on 2022-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.IntegerField(max_length=33)),
                ('last_name', models.IntegerField(max_length=33)),
                ('ph_num', models.IntegerField()),
                ('otp', models.IntegerField(max_length=6)),
            ],
        ),
    ]
