# Generated by Django 4.0.2 on 2022-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='ph_num',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
